apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../local

patches:
  - target:
      kind: TemporalConnection
      name: temporal-connection
      namespace: temporal-oms-processing
    patch: |-
      apiVersion: temporal.io/v1alpha1
      kind: TemporalConnection
      metadata:
        name: temporal-connection
        namespace: temporal-oms-processing
      spec:
        hostPort: host.k3d.internal:7233
