spring.config.import: classpath:acme.processing.yaml,optional:dotenv:.env.local
spring.application.name: processing-api
spring.temporal.start-workers: false

management.server.port: 9081

server.port: 8070

# Swagger/OpenAPI Configuration (MANDATORY per stack-api-rest)
springdoc:
  api-docs:
    path: /v3/api-docs
#  swagger-ui:
#    path: /docs  # Swagger UI at /docs
#    operationsSorter: method
#    tagsSorter: alpha
  show-actuator: false
