spring.config.import: classpath:acme.enablements.yaml
spring.profiles.default: local
server.port: -1
spring.application.name: enablements-workers
spring.temporal.start-workers: true
management.server.port: 9072
