spring.config.import: classpath:acme.fulfillment.yaml
spring.profiles.default: local
spring.application.name: fulfillment-api
spring.temporal.start-workers: false

management.server.port: 9071

server.port: 8060

enablements:
  api:
    base-url: ${ENABLEMENTS_API_BASE_URL:http://localhost:8050}

springdoc:
  api-docs:
    path: /v3/api-docs
  show-actuator: false
