---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-oms-config
  namespace: temporal-oms-apps
data:
  ENVIRONMENT: "local"
  TEMPORAL_ADDRESS: "temporal-frontend.temporal.svc.cluster.local:7233"
  TEMPORAL_TLS_ENABLED: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.opentelemetry-operator-system:4317"
  OTEL_SERVICE_NAME: "temporal-oms"
  DB_HOST: "postgres.temporal-oms-apps.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "temporal_oms_apps"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-oms-config
  namespace: temporal-oms-processing
data:
  ENVIRONMENT: "local"
  TEMPORAL_ADDRESS: "temporal-frontend.temporal.svc.cluster.local:7233"
  TEMPORAL_TLS_ENABLED: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.opentelemetry-operator-system:4317"
  OTEL_SERVICE_NAME: "temporal-oms"
  DB_HOST: "postgres.temporal-oms-processing.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "temporal_oms_processing"
