spring.config.import: classpath:acme.apps.yaml
spring.profiles.default: local
server.port: 8081
management.server.port: 9092
spring.temporal.start-workers: true
spring:
  application:
    name: apps-workers
easypost.api-key: ${EASYPOST_API_KEY:}