spring.config.import: classpath:acme.oms.yaml

spring.temporal:
    connection:
      # Connection settings
      target: ${TEMPORAL_ADDRESS:localhost:7233}

      # API Key for Temporal Cloud
      api-key: ${TEMPORAL_API_KEY:}

    namespace: ${TEMPORAL_NAMESPACE:processing}
    workers:
      - task-queue: processing
        workflow-classes:
          - com.acme.processing.workflows.OrderImpl
        activity-beans:
          - enrichment-activities
          - fulfillment-activities
        nexus-service-beans:
          - processing-service
        deployment-properties:
          use-versioning: true
          default-versioning-behavior: PINNED
          deployment-name: ${TEMPORAL_DEPLOYMENT_NAME:processing}
          build-id: ${TEMPORAL_WORKER_BUILD_ID:local}
      - task-queue: commerce-app
        activity-beans:
          - commerce-app-activities
        rate-limits:
          max-task-queue-activities-per-second: 150
        deployment-properties:
          use-versioning: true
          default-versioning-behavior: PINNED
          deployment-name: ${TEMPORAL_DEPLOYMENT_NAME:processing}
          build-id: ${TEMPORAL_WORKER_BUILD_ID:local}
      - task-queue: support
        workflow-classes:
          - com.acme.processing.workflows.SupportTeamImpl
        activity-beans:
          - support-activities
        deployment-properties:
          use-versioning: true
          default-versioning-behavior: PINNED
          deployment-name: ${TEMPORAL_DEPLOYMENT_NAME:processing}
          build-id: ${TEMPORAL_WORKER_BUILD_ID:local}

spring:
  kafka:
    topic: "order-fulfillment"
    groupId: "processing-service"