spring.config.import: classpath:acme.processing.yaml

spring.application.name: processing-workers
spring.main.web-application-type: reactive
spring.temporal.start-workers: true
server.port: 8071
management.server.port: 9082
