temporal:
  connection:
    # Temporal Cloud API key
    # Get from: https://cloud.temporal.io/settings/api-keys
    # This key is used for Worker Controller operations with the TemporalConnection CRD configuration
    #
    api-key: "<TEMPORAL CLOUD API KEY>"