#!/usr/bin/env python3
"""Generate python/fulfillment/src/converter/_registry.py.

Scans python/generated/pydantic/**/*_p2p.py for BaseModel subclasses,
pairs each with its _pb2 counterpart, and writes a typed REGISTRY dict.

Run from repo root:
    python scripts/gen_converter_registry.py

Invoke as part of proto generation (after buf generate):
    buf generate && python scripts/gen_converter_registry.py
"""
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
P2P_ROOT = REPO_ROOT / "python" / "generated" / "pydantic"
PB2_ROOT = REPO_ROOT / "python" / "generated"
OUTPUT = REPO_ROOT / "python" / "fulfillment" / "src" / "converter" / "_registry.py"


def basemodel_classes(path: Path) -> list[str]:
    """Return names of top-level BaseModel subclasses defined in the file."""
    tree = ast.parse(path.read_text())
    names: list[str] = []
    for node in tree.body:  # only top-level — nested classes are not accessible as module attrs
        if not isinstance(node, ast.ClassDef):
            continue
        for base in node.bases:
            base_name = (
                base.id if isinstance(base, ast.Name)
                else base.attr if isinstance(base, ast.Attribute)
                else None
            )
            if base_name == "BaseModel":
                names.append(node.name)
                break
    return names


def to_module(root: Path, path: Path) -> str:
    """Convert a file path to a dotted Python module name relative to root."""
    return str(path.relative_to(root)).removesuffix(".py").replace("/", ".")


def main() -> int:
    p2p_files = sorted(P2P_ROOT.rglob("*_p2p.py"))
    if not p2p_files:
        print(f"ERROR: no *_p2p.py files found under {P2P_ROOT}", file=sys.stderr)
        return 1

    imports: list[str] = []
    entries: list[tuple[int, str]] = []
    errors: list[str] = []

    for idx, p2p_path in enumerate(p2p_files):
        pb2_path = (PB2_ROOT / p2p_path.relative_to(P2P_ROOT)).with_name(
            p2p_path.name.replace("_p2p.py", "_pb2.py")
        )
        if not pb2_path.exists():
            errors.append(f"missing pb2 counterpart for {p2p_path.relative_to(REPO_ROOT)}")
            continue

        classes = basemodel_classes(p2p_path)
        if not classes:
            continue

        p2p_mod = to_module(P2P_ROOT, p2p_path)
        pb2_mod = to_module(PB2_ROOT, pb2_path)

        imports.append(f"import {p2p_mod} as _p2p_{idx}")
        imports.append(f"import {pb2_mod} as _pb2_{idx}")
        for cls in classes:
            entries.append((idx, cls))

    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1

    lines = [
        "# AUTO-GENERATED by scripts/gen_converter_registry.py — do not edit",
        "from __future__ import annotations",
        "",
        "from google.protobuf.message import Message",
        "from pydantic import BaseModel",
        "",
        *imports,
        "",
        "REGISTRY: dict[type[BaseModel], type[Message]] = {",
        *(f"    _p2p_{idx}.{cls}: _pb2_{idx}.{cls}," for idx, cls in entries),
        "}",
        "",
    ]

    OUTPUT.write_text("\n".join(lines))
    print(f"Wrote {len(entries)} entries across {len(imports) // 2} modules → {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
