apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-enablements-config
  namespace: temporal-oms-enablements
data:
  temporal-config.yaml: |
    spring.temporal.namespace: default
    spring.temporal.connection.target: host.docker.internal:7233
    enablements.api.base-url: http://enablements-api.temporal-oms-enablements.svc.cluster.local:8050
    enablements.apps-api.base-url: http://apps-api.temporal-oms-apps.svc.cluster.local
    enablements.processing-api.base-url: http://processing-api.temporal-oms-processing.svc.cluster.local
